#include "PlayerStateMachine.h"

void PlayerStateMachine::Attack()
{
	BEGIN_TRANSITION_MAP
		TRANSITION_MAP_ENTRY(ST_ATTACK) // ST_IDLE
		TRANSITION_MAP_ENTRY(ST_IGNORED) // ST_ATTACK
		TRANSITION_MAP_ENTRY(ST_ATTACK) // ST_DEFEND
		TRANSITION_MAP_ENTRY(ST_ATTACK) // ST_COUNTER
		TRANSITION_MAP_ENTRY(ST_ATTACK) // ST_EVADE
		TRANSITION_MAP_ENTRY(ST_ATTACK) // ST_BLOCk
	END_TRANSITION_MAP(NULL)
}

void PlayerStateMachine::Defend()
{
	BEGIN_TRANSITION_MAP
		TRANSITION_MAP_ENTRY(ST_DEFEND) // ST_IDLE
		TRANSITION_MAP_ENTRY(ST_DEFEND) // ST_ATTACK
		TRANSITION_MAP_ENTRY(ST_IGNORED) // ST_DEFEND
		TRANSITION_MAP_ENTRY(ST_DEFEND) // ST_COUNTER
		TRANSITION_MAP_ENTRY(ST_DEFEND) // ST_EVADE
		TRANSITION_MAP_ENTRY(ST_DEFEND) // ST_BLOCk
	END_TRANSITION_MAP(NULL)
}

void PlayerStateMachine::Counter()
{
	BEGIN_TRANSITION_MAP
		TRANSITION_MAP_ENTRY(ST_COUNTER) // ST_IDLE
		TRANSITION_MAP_ENTRY(ST_COUNTER) // ST_ATTACK
		TRANSITION_MAP_ENTRY(ST_COUNTER) // ST_DEFEND
		TRANSITION_MAP_ENTRY(ST_IGNORED) // ST_COUNTER
		TRANSITION_MAP_ENTRY(ST_COUNTER) // ST_EVADE
		TRANSITION_MAP_ENTRY(ST_COUNTER) // ST_BLOCk
	END_TRANSITION_MAP(NULL)
}

void PlayerStateMachine::Evade()
{
	BEGIN_TRANSITION_MAP
		TRANSITION_MAP_ENTRY(ST_EVADE) // ST_IDLE
		TRANSITION_MAP_ENTRY(ST_EVADE) // ST_ATTACK
		TRANSITION_MAP_ENTRY(ST_EVADE) // ST_DEFEND
		TRANSITION_MAP_ENTRY(ST_EVADE) // ST_COUNTER
		TRANSITION_MAP_ENTRY(ST_IGNORED) // ST_EVADE
		TRANSITION_MAP_ENTRY(ST_EVADE) // ST_BLOCk
	END_TRANSITION_MAP(NULL)
}

void PlayerStateMachine::Block()
{
	BEGIN_TRANSITION_MAP
		TRANSITION_MAP_ENTRY(ST_BLOCK) // ST_IDLE
		TRANSITION_MAP_ENTRY(ST_BLOCK) // ST_ATTACK
		TRANSITION_MAP_ENTRY(ST_BLOCK) // ST_DEFEND
		TRANSITION_MAP_ENTRY(ST_BLOCK) // ST_COUNTER
		TRANSITION_MAP_ENTRY(ST_BLOCK) // ST_EVADE
		TRANSITION_MAP_ENTRY(ST_IGNORED) // ST_BLOCk
	END_TRANSITION_MAP(NULL)
}

void PlayerStateMachine::ST_Idle(PlayerData*)
{
}

void PlayerStateMachine::ST_Attack(PlayerData*)
{
}

void PlayerStateMachine::ST_Defend(PlayerData*)
{
}

void PlayerStateMachine::ST_Counter(PlayerData*)
{
}

void PlayerStateMachine::ST_Evade(PlayerData*)
{
}

void PlayerStateMachine::ST_Block(PlayerData*)
{
}

